services:
  db:
    container_name: postgres_db
    image: postgres:alpine
    command: postgres -c listen_addresses=0.0.0.0
    networks:
      - xhost
    restart: always
    ports:
      - 5432:5432
    environment:
      SQLALCHEMY_DATABASE_URL_LOCAL: ${SQLALCHEMY_DATABASE_URL_LOCAL}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

  test_db:
    container_name: test_postgres_db
    image: postgres:alpine
    command: postgres -c listen_addresses=0.0.0.0
    networks:
      - xhost
    restart: always
    ports:
      - 5433:5432
    environment:
      TEST_SQLALCHEMY_DATABASE_URL_LOCAL: ${TEST_SQLALCHEMY_DATABASE_URL_LOCAL}
      POSTGRES_DB: ${TEST_DB_NAME}
      POSTGRES_USER: ${TEST_DB_USER}
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
    env_file:
      - .env
    volumes:
      - test_db_data:/var/lib/postgresql/data

  redis:
    container_name: redis_cache
    image: redis:alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - xhost
    ports:
      - '6379:6379'
    restart: always
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    env_file:
      - .env
    volumes:
      - cache_data:/cache
networks:
  xhost:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24

volumes:
  db_data:
  test_db_data:
  cache_data:
